### ISSUE TITLE
De-board Bijal Sanghani from OC 

### ISSUE THREAD

**Issue by ghankins** [peeringdb/outreachcom#10]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from outreachcom mailing list
- [x] close peeringdb.com email address
- [x] remove from oc page in PDB deck
- [x] remove from oc page on docs.peeringdb.com
- [x]  reassign github issues
- [x] remove from peeringdb github team

**Comment by ghankins** [comment]
- [x] remove from Slack
- [x] remove from outreachcom mailing list
- [x] remove from oc page in PDB deck
- [x] remove from oc page on docs.peeringdb.com

**Comment by arnoldnipper** [comment]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] reassign github issues
- [x] remove from peeringdb github team
