### ISSUE TITLE
De-board Jonathan Martone from OC

### ISSUE THREAD

**Issue by ghankins** [peeringdb/outreachcom#13]
- [x] remove peeringdb.com email address
- [x] remove from Slack
- [x] remove from outreachcom mailing list
- [x] remove from  outreach page in PDB deck
- [x] remove from  outreach page on docs.peeringdb.com

**Comment by ccaputo** [comment]
- [x] remove peeringdb.com email address
- [x] remove from outreachcom mailing list

**Comment by ghankins** [comment]
- [x] remove from Slack
- [x] remove from outreach page on docs.peeringdb.com

**Comment by ghankins** [comment]
- [x] remove from outreach page in PDB deck
