### ISSUE TITLE
De-board Rebecca Stanić from OC

### ISSUE THREAD

**Issue by ghankins** [peeringdb/outreachcom#4]
- [x] remove from outreachcom mailing list
- [x] close peeringdb.com email address
- [x] remove from peeringdb slack
- [x] remove from outreachcom page in docs.peeringdb.com
- [x] redistribute assigned issues - didn't find any in GitHub
- [x] remove from outreachcom page in PDB deck
- [x] remove from peeringdb github team - didn't find in GitHub

**Comment by ghankins** [comment]
- [x] remove from outreachcom mailing list
- [x] remove from peeringdb slack
- [x] remove from outreachcom page in docs.peeringdb.com
- [x] remove from outreachcom page in PDB deck

**Comment by ccaputo** [comment]
- [x] close peeringdb.com email address
- [x] redistribute assigned issues - didn't find any in GitHub
- [x] remove from outreachcom page in PDB deck
- [x] remove from peeringdb github team - didn't find in GitHub
