### ISSUE TITLE
De-board Inga Turner from OC

### ISSUE THREAD

**Issue by ghankins** [peeringdb/outreachcom#8]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from outreachcom mailing list - already done by someone else
- [x] close peeringdb.com email address
- [x] remove from oc page in PDB deck
- [x] remove from oc page on docs.peeringdb.com
- [x]  reassign github issues
- [x] remove from peeringdb github team

**Comment by ghankins** [comment]
- [x] remove from Slack
- [x] remove from outreachcom mailing list - already done by someone else
- [x] remove from oc page in PDB deck
- [x] remove from oc page on docs.peeringdb.com

**Comment by ccaputo** [comment]
Email suspended and will be deleted in a few weeks. No github found.

**Comment by arnoldnipper** [comment]
- [x] deskpro n/a
- [x] downgrade peeringdb user n/a
